---
name: Release

on:  # yamllint disable rule:truthy
  push:
    tags:
      - "*.*.*"

jobs:
  tests:
    strategy:
      matrix:
        bazel-version:
          - 6.x
          - 7.x
          - 8.0.0rc4
        runner:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          echo "USE_BAZEL_VERSION=${BAZEL_VERSION}" > .bazeliskrc
        env:
          BAZEL_VERSION: ${{matrix.bazel-version}}
        working-directory: tests/bcr

      - name: Install bazelisk
        uses: yuyawk/github-actions/install-bazelisk@v1

      - name: Test
        run: bazel query "tests(//...)" | xargs -n1 bazel test
        working-directory: tests/bcr

      - name: Test run fmt
        run: bazel query 'kind("tf_format rule", //...)' | xargs -n1 bazel run
        working-directory: tests/bcr

      - name: Test run gendoc
        run: bazel query 'kind("tf_gen_doc rule", //...)' | xargs -n1 bazel run
        working-directory: tests/bcr

      - name: Test run genversions
        run: |
          bazel query 'kind(tf_gen_version, //...)' | xargs bazel build
          bazel cquery 'kind(tf_gen_versions, //...)' --output files | xargs -n1 bash

  pkg:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release archive and notes
        run: |
          scripts/package_distro.sh

      - name: Archive release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            bazel-bin/distro/*.tar.gz
            bazel-bin/distro/relnotes.md
          retention-days: 5

  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: pkg
    permissions:
      contents: write
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: relnotes.md
          fail_on_unmatched_files: true
          files: rules_tf-*.tar.gz
